repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    # Run the formatter.
    -   id: ruff-format
    # Run import sorting fixes after formatting to align with README command.
    -   id: ruff
        name: ruff-fix-imports
        args: [--fix, --exit-non-zero-on-fix, --select, I]
