version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - "${FRONTEND_HOST_PORT:-3000}:${FRONTEND_CONTAINER_PORT:-3000}"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    ports:
      - "${BACKEND_HOST_PORT:-8000}:${BACKEND_CONTAINER_PORT:-8000}"
    environment:
      - PYTHONUNBUFFERED=1
      - LM_STUDIO_ENDPOINT=http://lmstudio:1234/v1
    restart: unless-stopped

  lmstudio:
    build:
      context: .
      dockerfile: .docker/lmstudio/Dockerfile
    ports:
      - "${LMSTUDIO_HOST_PORT:-1234}:${LMSTUDIO_CONTAINER_PORT:-1234}"
    restart: unless-stopped
